{
 "title": "Gamelift servers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Europe",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"EU.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  },
  {
   "title": "Europe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"EU.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  },
  {
   "title": "Asia Pacific",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"AP.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  },
  {
   "title": "Asia Pacific",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"AP.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  },
  {
   "title": "United States",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"US.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  },
  {
   "title": "United States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"US.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  },
  {
   "title": "Canada",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"CA.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  },
  {
   "title": "Canada",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\r\n  {job=\"foggler\"}\r\n  |~ \"CA.*\"\r\n  | json\r\n  | unwrap fields_ping\r\n  [${__interval}]\r\n) by (fields_server)\r\n"
    }
   ]
  }
 ]
}