[servers]
"Asia Pacific (Hong Kong)" = "ec2.ap-east-1.amazonaws.com"
"Asia Pacific (Mumbai)" = "gamelift.ap-south-1.amazonaws.com"
"Asia Pacific (Tokyo)" = "gamelift.ap-northeast-1.amazonaws.com"
"Asia Pacific (Seoul)" = "gamelift.ap-northeast-2.amazonaws.com"
"Asia Pacific (Singapore)" = "gamelift.ap-southeast-1.amazonaws.com"
"Asia Pacific (Sydney)" = "gamelift.ap-southeast-2.amazonaws.com"
"Canada (Central)" = "gamelift.ca-central-1.amazonaws.com"
"Europe (Frankfurt)" = "gamelift.eu-central-1.amazonaws.com"
"Europe (Ireland)" = "gamelift.eu-west-1.amazonaws.com"
"Europe (London)" = "gamelift.eu-west-2.amazonaws.com"
"South America (São Paulo)" = "gamelift.sa-east-1.amazonaws.com"
"US East (North Virginia)" = "gamelift.us-east-1.amazonaws.com"
"US East (Ohio)" = "gamelift.us-east-2.amazonaws.com"
"US West (North California)" = "gamelift.us-west-1.amazonaws.com"
"US West (Oregon)" = "gamelift.us-west-2.amazonaws.com"
