[servers]
"AP East 1" = "ec2.ap-east-1.amazonaws.com"
"AP South 1" = "gamelift.ap-south-1.amazonaws.com"
"AP North East 1" = "gamelift.ap-northeast-1.amazonaws.com"
"AP North East 2" = "gamelift.ap-northeast-2.amazonaws.com"
"AP South East 1" = "gamelift.ap-southeast-1.amazonaws.com"
"AP South East 2" = "gamelift.ap-southeast-2.amazonaws.com"
"CA 1" = "gamelift.ca-central-1.amazonaws.com"
"EU Central 1" = "gamelift.eu-central-1.amazonaws.com"
"EU West 1" = "gamelift.eu-west-1.amazonaws.com"
"EU West 2" = "gamelift.eu-west-2.amazonaws.com"
"SA East" = "gamelift.sa-east-1.amazonaws.com"
"US East 1" = "gamelift.us-east-1.amazonaws.com"
"US East 2" = "gamelift.us-east-2.amazonaws.com"
"US West 1" = "gamelift.us-west-1.amazonaws.com"
"US West 2" = "gamelift.us-west-2.amazonaws.com"
