name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-foggler-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, Run and Push Docker Image
        run: |
          docker build ./foggler --tag ghcr.io/${{ github.repository_owner }}/foggler:latest
          docker run ghcr.io/${{ github.repository_owner }}/foggler:latest
          docker push ghcr.io/${{ github.repository_owner }}/foggler:latest
